import { ANDROID_STRINGS } from './android_strings.js';

const translations = {
  fr: {
    subtitle:'Comparaison multi-modèles', cities:'Mes villes', addCity:'Ajouter une ville', settings:'Paramètres', refresh:'Actualiser',
    emptyTitle:'Aucune ville favorite', emptyBody:'Ajoutez une ville pour comparer les scénarios de plusieurs modèles météo.',
    searchCity:'Rechercher une ville', searchPlaceholder:'Paris, Lyon, Bruxelles…', models:'modèles', updated:'Mis à jour', offline:'Hors connexion — affichage du cache local.',
    today:'Aujourd’hui', temperature:'Température', precipitation:'Précipitations', wind:'Vent', gusts:'Rafales', agreement:'Accord', range:'Plage',
    forecastTimeline:'Chronologie', confidenceBand:'Bande d’accord horaire', detailedComparison:'Comparaison détaillée', reliability:'Fiabilité locale', evolution:'Évolution des prévisions',
    daily:'Par jour', hourly:'Par heure', conditions:'Conditions', theme:'Apparence', language:'Langue', refreshInterval:'Actualisation automatique', weatherModels:'Modèles météo',
    sortZone:'Zone', sortFamily:'Famille', sortResolution:'Finesse', about:'À propos', privacy:'Confidentialité', support:'Soutenir le développement',
    biasRefresh:'Actualiser l’historique de biais', biasDesc:'Télécharge les prévisions J+1 archivées et leur référence historique pour calculer le biais local.',
    light:'Clair', dark:'Sombre', system:'Système', manual:'Manuel', noData:'Pas de données', loading:'Chargement…', close:'Fermer', back:'Retour', remove:'Retirer',
    whyAgreement:'Pourquoi cet accord ?', noWidgets:'Les widgets Android Glance ne sont pas inclus dans la version web.',
    high:'élevé', medium:'moyen', low:'faible', source:'Données : Open-Meteo. Aucun tracker publicitaire ajouté.',
    biasNotReady:'Historique insuffisant', dry:'sec', rain:'pluie', divided:'partagé', sunrise:'Lever', sunset:'Coucher',
    webHomeIntro:'Prévisions brutes, dispersion inter-modèles, évolution et biais local — sans masquer les désaccords.', noCache:'Aucune donnée en cache.',
    webRefreshDesc:'Seuil de fraîcheur du cache au chargement. Une actualisation manuelle force toujours une nouvelle requête.',
    webPrivacyBody:'Les favoris, réglages, caches, historiques de biais et snapshots d’évolution restent dans le stockage local du navigateur. Les appels météo sont envoyés uniquement aux API Open-Meteo.',
    webAboutBody:'Port web de MeteoCompare Android v1.8.0 : comparaison multi-modèles, cache local, biais local et évolution des prévisions.', clearLocalData:'Effacer les données locales',
    webDetailedDesc:'Données brutes par modèle. Les cellules absentes restent absentes.', webBiasDesc:'Prévisions J+1 passées comparées à la référence historique Open-Meteo. Le biais ne modifie jamais les valeurs brutes affichées.',
    webNoBand:'Pas assez de modèles pour calculer une bande.', webNormals:'Repères ERA5 sur 10 ans', webLoading:'chargement…', webUnavailableOffline:'indisponibles hors ligne.',
  },
  en: {
    subtitle:'Multi-model comparison', cities:'My cities', addCity:'Add a city', settings:'Settings', refresh:'Refresh',
    emptyTitle:'No favorite city', emptyBody:'Add a city to compare scenarios from several weather models.',
    searchCity:'Search for a city', searchPlaceholder:'Paris, London, Berlin…', models:'models', updated:'Updated', offline:'Offline — showing local cache.',
    today:'Today', temperature:'Temperature', precipitation:'Precipitation', wind:'Wind', gusts:'Gusts', agreement:'Agreement', range:'Range',
    forecastTimeline:'Timeline', confidenceBand:'Hourly agreement band', detailedComparison:'Detailed comparison', reliability:'Local reliability', evolution:'Forecast evolution',
    daily:'Daily', hourly:'Hourly', conditions:'Conditions', theme:'Appearance', language:'Language', refreshInterval:'Automatic refresh', weatherModels:'Weather models',
    sortZone:'Zone', sortFamily:'Family', sortResolution:'Resolution', about:'About', privacy:'Privacy', support:'Support development',
    biasRefresh:'Refresh bias history', biasDesc:'Downloads archived D+1 forecasts and historical reference data to compute local bias.',
    light:'Light', dark:'Dark', system:'System', manual:'Manual', noData:'No data', loading:'Loading…', close:'Close', back:'Back', remove:'Remove',
    whyAgreement:'Why this agreement?', noWidgets:'Android Glance widgets are intentionally not included in the web version.',
    high:'high', medium:'medium', low:'low', source:'Data: Open-Meteo. No advertising tracker added.',
    biasNotReady:'Not enough history', dry:'dry', rain:'rain', divided:'divided', sunrise:'Sunrise', sunset:'Sunset',
    webHomeIntro:'Raw forecasts, inter-model spread, evolution and local bias — without hiding disagreements.', noCache:'No cached data.',
    webRefreshDesc:'Cache freshness threshold at page load. A manual refresh always forces a new request.',
    webPrivacyBody:'Favorites, settings, forecast caches, bias history and evolution snapshots stay in this browser’s local storage. Weather requests are sent only to Open-Meteo APIs.',
    webAboutBody:'Web port of MeteoCompare Android v1.8.0: multi-model comparison, local cache, local bias and forecast evolution.', clearLocalData:'Clear local data',
    webDetailedDesc:'Raw values by model. Missing cells remain missing.', webBiasDesc:'Past D+1 forecasts compared with the Open-Meteo historical reference. Bias never alters displayed raw values.',
    webNoBand:'Not enough models to compute a band.', webNormals:'10-year ERA5 references', webLoading:'loading…', webUnavailableOffline:'unavailable offline.',
  },
  es: { subtitle:'Comparación multimodelo', cities:'Mis ciudades', addCity:'Añadir ciudad', settings:'Ajustes', refresh:'Actualizar', emptyTitle:'Sin ciudades favoritas', emptyBody:'Añade una ciudad para comparar varios modelos meteorológicos.', searchCity:'Buscar ciudad', searchPlaceholder:'Madrid, París, Roma…', models:'modelos', today:'Hoy', temperature:'Temperatura', precipitation:'Precipitación', wind:'Viento', gusts:'Ráfagas', agreement:'Acuerdo', detailedComparison:'Comparación detallada', reliability:'Fiabilidad local', evolution:'Evolución del pronóstico', daily:'Por día', hourly:'Por hora', conditions:'Condiciones', theme:'Apariencia', language:'Idioma', refreshInterval:'Actualización automática', weatherModels:'Modelos meteorológicos', sortZone:'Zona', sortFamily:'Familia', sortResolution:'Resolución', about:'Acerca de', privacy:'Privacidad', support:'Apoyar el desarrollo', loading:'Cargando…', close:'Cerrar', back:'Atrás', remove:'Eliminar', system:'Sistema', light:'Claro', dark:'Oscuro', manual:'Manual', webHomeIntro:'Pronósticos brutos, dispersión entre modelos, evolución y sesgo local, sin ocultar los desacuerdos.', noCache:'No hay datos en caché.', webRefreshDesc:'Umbral de frescura de la caché al cargar. Una actualización manual fuerza siempre una nueva solicitud.', webPrivacyBody:'Favoritos, ajustes, cachés, historial de sesgo y capturas de evolución permanecen en el almacenamiento local del navegador. Las solicitudes meteorológicas se envían solo a Open-Meteo.', webAboutBody:'Versión web de MeteoCompare Android v1.8.0: comparación multimodelo, caché local, sesgo local y evolución del pronóstico.', clearLocalData:'Borrar datos locales', webDetailedDesc:'Datos brutos por modelo. Las celdas ausentes siguen ausentes.', webBiasDesc:'Pronósticos D+1 anteriores comparados con la referencia histórica de Open-Meteo. El sesgo nunca modifica los valores brutos mostrados.', webNoBand:'No hay suficientes modelos para calcular una banda.', webNormals:'Referencias ERA5 de 10 años', webLoading:'cargando…', webUnavailableOffline:'no disponibles sin conexión.' },
  de: { subtitle:'Multi-Modell-Vergleich', cities:'Meine Städte', addCity:'Stadt hinzufügen', settings:'Einstellungen', refresh:'Aktualisieren', emptyTitle:'Keine Favoriten', emptyBody:'Füge eine Stadt hinzu, um mehrere Wettermodelle zu vergleichen.', searchCity:'Stadt suchen', searchPlaceholder:'Berlin, Paris, Wien…', models:'Modelle', today:'Heute', temperature:'Temperatur', precipitation:'Niederschlag', wind:'Wind', gusts:'Böen', agreement:'Übereinstimmung', detailedComparison:'Detailvergleich', reliability:'Lokale Zuverlässigkeit', evolution:'Vorhersageentwicklung', daily:'Täglich', hourly:'Stündlich', conditions:'Bedingungen', theme:'Darstellung', language:'Sprache', refreshInterval:'Automatische Aktualisierung', weatherModels:'Wettermodelle', sortZone:'Zone', sortFamily:'Familie', sortResolution:'Auflösung', about:'Über', privacy:'Datenschutz', support:'Entwicklung unterstützen', loading:'Laden…', close:'Schließen', back:'Zurück', remove:'Entfernen', system:'System', light:'Hell', dark:'Dunkel', manual:'Manuell', webHomeIntro:'Rohprognosen, Modellstreuung, Entwicklung und lokaler Bias – ohne Meinungsverschiedenheiten zu verbergen.', noCache:'Keine Cache-Daten.', webRefreshDesc:'Frischegrenze des Caches beim Laden. Eine manuelle Aktualisierung erzwingt immer eine neue Anfrage.', webPrivacyBody:'Favoriten, Einstellungen, Caches, Bias-Verlauf und Entwicklungssnapshots bleiben im lokalen Browserspeicher. Wetteranfragen gehen nur an Open-Meteo.', webAboutBody:'Web-Port von MeteoCompare Android v1.8.0: Multi-Modell-Vergleich, lokaler Cache, lokaler Bias und Prognoseentwicklung.', clearLocalData:'Lokale Daten löschen', webDetailedDesc:'Rohdaten je Modell. Fehlende Zellen bleiben fehlend.', webBiasDesc:'Frühere D+1-Prognosen im Vergleich zur historischen Open-Meteo-Referenz. Der Bias verändert niemals die angezeigten Rohwerte.', webNoBand:'Nicht genügend Modelle für ein Band.', webNormals:'ERA5-Referenzen über 10 Jahre', webLoading:'wird geladen…', webUnavailableOffline:'offline nicht verfügbar.' },
  it: { subtitle:'Confronto multi-modello', cities:'Le mie città', addCity:'Aggiungi città', settings:'Impostazioni', refresh:'Aggiorna', emptyTitle:'Nessuna città preferita', emptyBody:'Aggiungi una città per confrontare più modelli meteo.', searchCity:'Cerca città', searchPlaceholder:'Roma, Parigi, Milano…', models:'modelli', today:'Oggi', temperature:'Temperatura', precipitation:'Precipitazioni', wind:'Vento', gusts:'Raffiche', agreement:'Accordo', detailedComparison:'Confronto dettagliato', reliability:'Affidabilità locale', evolution:'Evoluzione delle previsioni', daily:'Giornaliero', hourly:'Orario', conditions:'Condizioni', theme:'Aspetto', language:'Lingua', refreshInterval:'Aggiornamento automatico', weatherModels:'Modelli meteo', sortZone:'Zona', sortFamily:'Famiglia', sortResolution:'Risoluzione', about:'Informazioni', privacy:'Privacy', support:'Sostieni lo sviluppo', loading:'Caricamento…', close:'Chiudi', back:'Indietro', remove:'Rimuovi', system:'Sistema', light:'Chiaro', dark:'Scuro', manual:'Manuale', webHomeIntro:'Previsioni grezze, dispersione tra modelli, evoluzione e bias locale, senza nascondere i disaccordi.', noCache:'Nessun dato in cache.', webRefreshDesc:'Soglia di freschezza della cache al caricamento. Un aggiornamento manuale forza sempre una nuova richiesta.', webPrivacyBody:'Preferiti, impostazioni, cache, cronologia del bias e snapshot dell’evoluzione restano nell’archiviazione locale del browser. Le richieste meteo vengono inviate solo a Open-Meteo.', webAboutBody:'Port web di MeteoCompare Android v1.8.0: confronto multi-modello, cache locale, bias locale ed evoluzione delle previsioni.', clearLocalData:'Cancella dati locali', webDetailedDesc:'Dati grezzi per modello. Le celle mancanti restano mancanti.', webBiasDesc:'Previsioni D+1 passate confrontate con il riferimento storico Open-Meteo. Il bias non modifica mai i valori grezzi mostrati.', webNoBand:'Modelli insufficienti per calcolare una banda.', webNormals:'Riferimenti ERA5 su 10 anni', webLoading:'caricamento…', webUnavailableOffline:'non disponibili offline.' },
};

export function languageCode(pref) {
  if (pref === 'FRENCH') return 'fr'; if (pref === 'ENGLISH') return 'en'; if (pref === 'SPANISH') return 'es'; if (pref === 'GERMAN') return 'de'; if (pref === 'ITALIAN') return 'it';
  const sys=(navigator.language||'fr').slice(0,2).toLowerCase();return translations[sys]?sys:'fr';
}
export function makeI18n(pref) {
  const lang=languageCode(pref), dict={...(ANDROID_STRINGS.fr||{}),...translations.fr,...(ANDROID_STRINGS[lang]||{}),...translations[lang]};
  return {lang,locale:lang==='fr'?'fr-FR':lang==='en'?'en-GB':`${lang}-${lang.toUpperCase()}`,t:(k)=>dict[k]||translations.fr[k]||k};
}
