const $=selector=>document.querySelector(selector);
let days=30,currentAnalytics=null,currentStatus=null;
const nf=new Intl.NumberFormat('fr-FR'),decimal=new Intl.NumberFormat('fr-FR',{maximumFractionDigits:1});

async function api(path,options={}){const r=await fetch(path,{...options,headers:{'content-type':'application/json',...(options.headers||{})},cache:'no-store'});let body={};try{body=await r.json();}catch{}if(r.status===401){showLogin();throw new Error('UNAUTHORIZED');}if(!r.ok)throw new Error(body.error||`HTTP_${r.status}`);return body;}
function showLogin(){$('#login').hidden=false;$('#dashboard').hidden=true;$('#logout').hidden=true;const version=$('#deployed-version');if(version)version.hidden=true;setExportEnabled(false);}
function showDashboard(){$('#login').hidden=true;$('#not-configured').hidden=true;$('#dashboard').hidden=false;$('#logout').hidden=false;}
function fmt(n){return nf.format(Number(n)||0);}
function fmt1(n){return decimal.format(Number(n)||0);}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function pct(value){return `${fmt1(value)} %`;}
function ratio(a,b){return Number(b)>0?Number(a)/Number(b):0;}
function change(current,previous){current=Number(current)||0;previous=Number(previous)||0;if(previous===0)return current===0?0:null;return (current-previous)/previous*100;}
function deltaMarkup(current,previous){const delta=change(current,previous);if(delta==null)return '<span class="metric-delta neutral">Nouvelle activité</span>';const rounded=Math.abs(delta)<.05?0:delta,cls=rounded>0?'up':rounded<0?'down':'neutral',arrow=rounded>0?'↑':rounded<0?'↓':'→';return `<span class="metric-delta ${cls}">${arrow} ${fmt1(Math.abs(rounded))} % <small>vs période précédente</small></span>`;}
function dateFr(value,options={day:'numeric',month:'short'}){try{return new Intl.DateTimeFormat('fr-FR',options).format(new Date(value));}catch{return String(value||'');}}
function dateRangeLabel(period){if(!period?.from||!period?.to)return '';const from=dateFr(period.from,{day:'numeric',month:'long',year:'numeric'}),to=dateFr(period.to,{day:'numeric',month:'long',year:'numeric'});return `${from} — ${to}`;}
function humanLabel(value,type='generic'){
  const raw=String(value??'—');if(raw==='—')return type==='referrer'?'Direct':'Non renseigné';
  const maps={device:{desktop:'Ordinateur',mobile:'Mobile',tablet:'Tablette',other:'Autre'},browser:{chrome:'Chrome',firefox:'Firefox',safari:'Safari',edge:'Edge',other:'Autre'},os:{windows:'Windows',macos:'macOS',ios:'iOS',android:'Android',linux:'Linux',chromeos:'ChromeOS',other:'Autre'},language:{fr:'Français',en:'Anglais',es:'Espagnol',de:'Allemand',it:'Italien',other:'Autre'},display:{browser:'Navigateur',standalone:'Application installée'},navigation:{seo:'Page ville SEO',spa:'Navigation SPA',direct:'Accès direct'},theme:{light:'Clair',dark:'Sombre'},density:{comfortable:'Confortable',compact:'Compact'},client:{web:'Web',android:'Android',unknown:'Non identifié'},cache:{hit:'Cache Worker',miss:'Appel Météo-France',error:'Erreur amont',none:'Sans cache'}};
  return maps[type]?.[raw.toLowerCase()]||raw;
}
function countryLabel(code){const text=String(code||'—').toUpperCase();if(!/^[A-Z]{2}$/.test(text))return humanLabel(text);const flag=String.fromCodePoint(...[...text].map(c=>127397+c.charCodeAt(0)));let name=text;try{name=new Intl.DisplayNames(['fr'],{type:'region'}).of(text)||text;}catch{}return `${flag} ${name}`;}
function list(selector,items,{type='generic',withVisitors=false,emptyMessage='Aucune donnée sur cette période.'}={}){const target=$(selector);if(!items?.length){target.innerHTML=`<p class="empty">${escapeHtml(emptyMessage)}</p>`;return;}const max=Math.max(...items.map(item=>Number(item.value)||0),1);target.innerHTML=items.map(item=>{const label=type==='country'?countryLabel(item.label):humanLabel(item.label,type),secondary=withVisitors&&Number.isFinite(Number(item.visitors))?`<span>${fmt(item.visitors)} visiteurs</span>`:'';return `<div class="list-row"><div class="list-main"><div class="list-label"><span title="${escapeHtml(label)}">${escapeHtml(label)}</span>${secondary}</div><progress max="${max}" value="${Number(item.value)||0}"></progress></div><strong>${fmt(item.value)}</strong></div>`;}).join('');}
function path(points){return points.map((p,i)=>`${i?'L':'M'}${p[0].toFixed(1)},${p[1].toFixed(1)}`).join(' ');}

function chartTooltip(target){let tooltip=target.querySelector('.chart-tooltip');if(!tooltip){tooltip=document.createElement('div');tooltip.className='chart-tooltip';tooltip.hidden=true;target.appendChild(tooltip);}return tooltip;}
function bindCartesianHover(target,rows,{width,left,right,mode='points',lineSelector='.chart-hover-line',content}){
  const svg=target.querySelector('svg'),line=target.querySelector(lineSelector),tooltip=chartTooltip(target);if(!svg||!rows.length)return;
  const show=(event,index)=>{const row=rows[index];if(!row)return;const box=svg.getBoundingClientRect(),targetBox=target.getBoundingClientRect(),plotW=width-left-right,xView=mode==='slots'?left+(index+.5)*plotW/rows.length:left+(rows.length===1?plotW/2:index*plotW/(rows.length-1)),xPx=xView/width*box.width+(box.left-targetBox.left);line?.removeAttribute('hidden');line?.setAttribute('x1',xView);line?.setAttribute('x2',xView);tooltip.innerHTML=content(row,index);tooltip.hidden=false;const desired=xPx+12,tipW=tooltip.offsetWidth||180;tooltip.style.left=`${Math.max(6,Math.min(targetBox.width-tipW-6,desired))}px`;tooltip.style.top='12px';};
  const indexFromPointer=event=>{const box=svg.getBoundingClientRect(),viewX=(event.clientX-box.left)/Math.max(1,box.width)*width,plotW=width-left-right;if(mode==='slots')return Math.max(0,Math.min(rows.length-1,Math.floor((viewX-left)/plotW*rows.length)));return Math.max(0,Math.min(rows.length-1,Math.round((viewX-left)/plotW*Math.max(1,rows.length-1))));};
  target.onpointermove=event=>show(event,indexFromPointer(event));target.onpointerleave=()=>{tooltip.hidden=true;line?.setAttribute('hidden','');};
}
function bindDonutHover(target,items,total){const tooltip=chartTooltip(target),segments=[...target.querySelectorAll('[data-donut-index]')];for(const segment of segments){const show=event=>{const item=items[Number(segment.dataset.donutIndex)];if(!item)return;tooltip.innerHTML=`<strong>${escapeHtml(humanLabel(item.label,'device'))}</strong><span>${fmt(item.value)} pages vues · ${pct(ratio(item.value,total)*100)}</span>`;tooltip.hidden=false;const rect=target.getBoundingClientRect();tooltip.style.left=`${Math.max(6,Math.min(rect.width-(tooltip.offsetWidth||170)-6,event.clientX-rect.left+10))}px`;tooltip.style.top=`${Math.max(6,event.clientY-rect.top-18)}px`;};segment.addEventListener('pointerenter',show);segment.addEventListener('pointermove',show);segment.addEventListener('pointerleave',()=>{tooltip.hidden=true;});segment.addEventListener('focus',event=>show({clientX:target.getBoundingClientRect().left+target.clientWidth/2,clientY:target.getBoundingClientRect().top+45}));segment.addEventListener('blur',()=>{tooltip.hidden=true;});}}

function renderTrend(data){const target=$('#trend-chart'),rows=data.trend||[];if(!rows.length){target.innerHTML='<p class="empty">Aucune donnée.</p>';return;}const width=920,height=270,p={l:46,r:16,t:22,b:38},plotW=width-p.l-p.r,plotH=height-p.t-p.b,max=Math.max(1,...rows.flatMap(r=>[Number(r.pageviews)||0,Number(r.visitors)||0])),x=i=>p.l+(rows.length===1?plotW/2:i*plotW/(rows.length-1)),y=v=>p.t+plotH-(Number(v)||0)/max*plotH,pagePts=rows.map((r,i)=>[x(i),y(r.pageviews)]),visitorPts=rows.map((r,i)=>[x(i),y(r.visitors)]),area=`M${p.l},${p.t+plotH} ${path(pagePts).replace(/^M/,'L')} L${p.l+plotW},${p.t+plotH} Z`;
  const grid=[0,.25,.5,.75,1].map(q=>{const value=Math.round(max*q),yy=y(value);return `<line class="chart-gridline" x1="${p.l}" y1="${yy}" x2="${width-p.r}" y2="${yy}"/><text class="chart-axis-label" x="${p.l-8}" y="${yy+4}" text-anchor="end">${fmt(value)}</text>`;}).join('');
  const tickStep=Math.max(1,Math.ceil(rows.length/6)),ticks=rows.map((row,i)=>(i%tickStep===0||i===rows.length-1)?`<text class="chart-axis-label" x="${x(i)}" y="${height-12}" text-anchor="middle">${escapeHtml(dateFr(`${row.day}T12:00:00Z`,{day:'numeric',month:'short'}))}</text>`:'').join('');
  const dots=rows.length<=60?rows.map((r,i)=>`<circle class="chart-dot pageviews" cx="${x(i)}" cy="${y(r.pageviews)}" r="3"/>`).join(''):'';
  target.innerHTML=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Évolution quotidienne des pages vues et visiteurs">${grid}<path class="trend-area" d="${area}"/><path class="trend-line pageviews" d="${path(pagePts)}"/><path class="trend-line visitors" d="${path(visitorPts)}"/>${dots}<line class="chart-hover-line" y1="${p.t}" y2="${p.t+plotH}" hidden/>${ticks}</svg>`;
  bindCartesianHover(target,rows,{width,left:p.l,right:p.r,content:r=>`<strong>${escapeHtml(dateFr(`${r.day}T12:00:00Z`,{weekday:'long',day:'numeric',month:'long',year:'numeric'}))}</strong><span><b>${fmt(r.pageviews)}</b> pages vues</span><span><b>${fmt(r.visitors)}</b> visiteurs</span><span>${fmt(r.events)} interactions</span>`});
}
function renderHourly(rows){const target=$('#hourly-chart');if(!rows?.length){target.innerHTML='<p class="empty">Aucune donnée.</p>';return;}const width=700,height=230,p={l:38,r:12,t:18,b:38},plotW=width-p.l-p.r,plotH=height-p.t-p.b,max=Math.max(1,...rows.flatMap(r=>[Number(r.pageviews)||0,Number(r.visitors)||0])),slot=plotW/rows.length,barW=Math.max(4,slot*.58),x=i=>p.l+i*slot+slot/2,y=v=>p.t+plotH-(Number(v)||0)/max*plotH;
  const grid=[0,.5,1].map(q=>{const value=Math.round(max*q),yy=y(value);return `<line class="chart-gridline" x1="${p.l}" y1="${yy}" x2="${width-p.r}" y2="${yy}"/><text class="chart-axis-label" x="${p.l-7}" y="${yy+4}" text-anchor="end">${fmt(value)}</text>`;}).join('');
  const bars=rows.map((r,i)=>{const yy=y(r.pageviews),h=p.t+plotH-yy;return `<rect class="hour-bar" x="${(x(i)-barW/2).toFixed(1)}" y="${yy.toFixed(1)}" width="${barW.toFixed(1)}" height="${Math.max(0,h).toFixed(1)}" rx="3"/>`;}).join('');
  const visitorPts=rows.map((r,i)=>[x(i),y(r.visitors)]),visitorPath=path(visitorPts),visitorDots=rows.map((r,i)=>`<circle class="hour-dot" cx="${x(i).toFixed(1)}" cy="${y(r.visitors).toFixed(1)}" r="2.8"/>`).join(''),ticks=rows.map((r,i)=>i%4===0||i===rows.length-1?`<text class="chart-axis-label" x="${x(i)}" y="${height-12}" text-anchor="middle">${escapeHtml(dateFr(r.timestamp,{hour:'2-digit'}).replace(' h','h'))}</text>`:'').join('');
  target.innerHTML=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Activité des dernières 24 heures">${grid}${bars}<path class="hour-line-halo" d="${visitorPath}"/><path class="hour-line" d="${visitorPath}"/>${visitorDots}<line class="chart-hover-line" y1="${p.t}" y2="${p.t+plotH}" hidden/>${ticks}</svg>`;
  bindCartesianHover(target,rows,{width,left:p.l,right:p.r,mode:'slots',content:r=>`<strong>${escapeHtml(dateFr(r.timestamp,{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}))}</strong><span><b>${fmt(r.pageviews)}</b> pages vues</span><span><b>${fmt(r.visitors)}</b> visiteurs</span><span>${fmt(r.events)} interactions</span>`});
}
function renderDonut(selector,items){const target=$(selector),filtered=(items||[]).filter(x=>Number(x.value)>0);if(!filtered.length){target.innerHTML='<p class="empty">Aucune donnée.</p>';return;}const shown=filtered.slice(0,6),total=filtered.reduce((sum,x)=>sum+Number(x.value||0),0),radius=54,circ=2*Math.PI*radius;let offset=0;const segments=shown.map((item,index)=>{const share=Number(item.value)/total,len=share*circ,markup=`<circle class="donut-segment segment-${index}" data-donut-index="${index}" tabindex="0" cx="80" cy="80" r="${radius}" stroke-dasharray="${len.toFixed(2)} ${(circ-len).toFixed(2)}" stroke-dashoffset="${(-offset).toFixed(2)}"><title>${escapeHtml(humanLabel(item.label,'device'))} · ${fmt(item.value)} pages · ${pct(share*100)}</title></circle>`;offset+=len;return markup;}).join('');const legend=shown.map((item,index)=>`<div class="donut-legend-row"><i class="segment-bg-${index}"></i><span>${escapeHtml(humanLabel(item.label,'device'))}</span><strong>${pct(Number(item.value)/total*100)}</strong></div>`).join('');target.innerHTML=`<div class="donut-visual"><svg viewBox="0 0 160 160" role="img" aria-label="Répartition par appareil"><circle class="donut-track" cx="80" cy="80" r="${radius}"/>${segments}</svg><div class="donut-center"><strong>${fmt(total)}</strong><span>pages vues</span></div></div><div class="donut-legend">${legend}</div>`;bindDonutHover(target,shown,total);}

function renderMetrics(data){const s=data.summary||{},p=data.previousSummary||{},pagesPerVisitor=ratio(s.pageviews,s.visitors),avgVisitors=ratio(s.visitors,data.days),directShare=ratio(s.directPageviews,s.pageviews)*100,mobileShare=ratio(s.mobilePageviews,s.pageviews)*100;const cards=[
  ['Visiteurs uniques / jour',fmt(s.visitors),deltaMarkup(s.visitors,p.visitors),'Pseudonyme renouvelé chaque jour'],
  ['Pages vues',fmt(s.pageviews),deltaMarkup(s.pageviews,p.pageviews),`${fmt1(ratio(s.pageviews,data.days))} / jour`],
  ['Interactions',fmt(s.events),deltaMarkup(s.events,p.events),`${fmt1(ratio(s.events,s.visitors))} / visiteur`],
  ['Pages / visiteur',fmt1(pagesPerVisitor),'',`${fmt(s.pages)} pages distinctes`],
  ['Visiteurs moyens / jour',fmt1(avgVisitors),'',`${fmt(s.activeDays)} jours actifs sur ${fmt(data.days)}`],
  ['Trafic direct',pct(directShare),'',`${pct(mobileShare)} des pages vues sur mobile`],
];$('#metrics').innerHTML=cards.map(([label,value,delta,note],i)=>`<article class="metric card metric-${i}"><span class="metric-label">${escapeHtml(label)}</span><strong>${value}</strong>${delta}<small>${escapeHtml(note)}</small></article>`).join('');}
function renderFacts(data){const s=data.summary||{};$('#period-label').textContent=dateRangeLabel(data.period);$('#period-facts').innerHTML=`<div><span>Jours avec audience</span><strong>${fmt(s.activeDays)} / ${fmt(data.days)}</strong></div><div><span>Pays représentés</span><strong>${fmt(s.countries)}</strong></div><div><span>Pages distinctes</span><strong>${fmt(s.pages)}</strong></div><div><span>Part mobile</span><strong>${pct(ratio(s.mobilePageviews,s.pageviews)*100)}</strong></div>`;}
function renderWorkerTrend(worker){const target=$('#vigilance-trend-chart'),rows=worker?.trend||[];if(!rows.length||!rows.some(r=>Number(r.requests)>0)){target.innerHTML='<p class="empty">Aucune requête Vigilance enregistrée sur cette période.</p>';return;}const width=700,height=210,p={l:42,r:12,t:18,b:36},plotW=width-p.l-p.r,plotH=height-p.t-p.b,max=Math.max(1,...rows.map(r=>Number(r.requests)||0)),x=i=>p.l+(rows.length===1?plotW/2:i*plotW/(rows.length-1)),y=v=>p.t+plotH-(Number(v)||0)/max*plotH,pts=rows.map((r,i)=>[x(i),y(r.requests)]),area=`M${p.l},${p.t+plotH} ${path(pts).replace(/^M/,'L')} L${p.l+plotW},${p.t+plotH} Z`,grid=[0,.5,1].map(q=>{const value=Math.round(max*q),yy=y(value);return `<line class="chart-gridline" x1="${p.l}" y1="${yy}" x2="${width-p.r}" y2="${yy}"/><text class="chart-axis-label" x="${p.l-7}" y="${yy+4}" text-anchor="end">${fmt(value)}</text>`;}).join(''),step=Math.max(1,Math.ceil(rows.length/5)),ticks=rows.map((r,i)=>(i%step===0||i===rows.length-1)?`<text class="chart-axis-label" x="${x(i)}" y="${height-11}" text-anchor="middle">${escapeHtml(dateFr(`${r.day}T12:00:00Z`,{day:'numeric',month:'short'}))}</text>`:'').join('');target.innerHTML=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Requêtes quotidiennes du Worker Vigilance">${grid}<path class="worker-trend-area" d="${area}"/><path class="worker-trend-line" d="${path(pts)}"/>${rows.length<=60?rows.map((r,i)=>`<circle class="worker-trend-dot" cx="${x(i)}" cy="${y(r.requests)}" r="2.8"/>`).join(''):''}<line class="chart-hover-line" y1="${p.t}" y2="${p.t+plotH}" hidden/>${ticks}</svg>`;bindCartesianHover(target,rows,{width,left:p.l,right:p.r,content:r=>`<strong>${escapeHtml(dateFr(`${r.day}T12:00:00Z`,{weekday:'long',day:'numeric',month:'long'}))}</strong><span><b>${fmt(r.requests)}</b> requêtes</span><span>${fmt(r.successful)} succès · ${fmt(r.failed)} erreurs</span>`});}
function renderWorkerVigilance(data){const worker=data.workerVigilance||{},total=Number(worker.total)||0,successful=Number(worker.successful)||0,failed=Number(worker.failed)||0,cacheHit=Number((worker.cache||[]).find(item=>item.label==='hit')?.value)||0,android=Number((worker.clients||[]).find(item=>item.label==='android')?.value)||0,web=Number((worker.clients||[]).find(item=>item.label==='web')?.value)||0;$('#vigilance-kpis').innerHTML=`<article class="service-kpi card"><span>Requêtes</span><strong>${fmt(total)}</strong></article><article class="service-kpi card"><span>Taux de succès</span><strong>${total?pct(successful/total*100):'—'}</strong></article><article class="service-kpi card"><span>Servies du cache</span><strong>${total?pct(cacheHit/total*100):'—'}</strong></article><article class="service-kpi card ${failed?'warning':''}"><span>Android / Web</span><strong>${fmt(android)}<small> / ${fmt(web)}</small></strong></article>`;renderWorkerTrend(worker);list('#vigilance-clients',worker.clients,{type:'client',emptyMessage:'Aucune origine client enregistrée.'});list('#vigilance-cache',worker.cache,{type:'cache',emptyMessage:'Aucune résolution de cache enregistrée.'});}
function renderAnalytics(data){renderMetrics(data);renderFacts(data);renderTrend(data);renderHourly(data.hourly24);renderDonut('#devices-chart',data.devices);list('#pages',data.topPages,{withVisitors:true});list('#referrers',data.referrers,{type:'referrer',withVisitors:true});list('#countries',data.countries,{type:'country',withVisitors:true});list('#events',data.events,{withVisitors:true});list('#browsers',data.browsers,{type:'browser'});list('#operating-systems',data.operatingSystems,{type:'os'});list('#languages',data.languages,{type:'language'});list('#display-modes',data.displayModes,{type:'display'});list('#navigation-modes',data.navigationModes,{type:'navigation'});list('#themes',data.themes,{type:'theme'});list('#densities',data.densities,{type:'density'});list('#app-versions',data.appVersions);renderWorkerVigilance(data);$('#updated').textContent=`Mis à jour ${new Date(data.generatedAt).toLocaleString('fr-FR')}`;}
function renderServices(data){const version=$('#deployed-version');if(version){version.textContent=data.appVersion?`Version déployée · v${data.appVersion}`:'Version déployée · —';version.hidden=false;}const services=data.services||[],ok=services.filter(s=>s.ok),failed=services.filter(s=>!s.ok),latencies=ok.map(s=>Number(s.latencyMs)).filter(Number.isFinite),avg=latencies.length?latencies.reduce((a,b)=>a+b,0)/latencies.length:0,maxLatency=Math.max(1,...latencies);$('#service-summary').innerHTML=`<article class="service-kpi card"><span>Services opérationnels</span><strong>${ok.length}<small> / ${services.length}</small></strong></article><article class="service-kpi card"><span>Latence moyenne</span><strong>${fmt1(avg)}<small> ms</small></strong></article><article class="service-kpi card ${failed.length?'warning':''}"><span>Alertes</span><strong>${failed.length}</strong></article>`;$('#services').innerHTML=services.map(service=>{const latency=Number(service.latencyMs),detail=service.detail?escapeHtml(service.detail):service.ok?`HTTP ${service.status||200}`:service.status?`HTTP ${service.status}`:service.error==='timeout'?'Délai dépassé':'Indisponible';return `<article class="service card ${service.ok?'ok':'failed'}"><div class="service-head"><span class="status-dot" aria-hidden="true"></span><div class="service-copy"><strong>${escapeHtml(service.name)}</strong><small>${detail}</small></div><span class="status-badge">${service.ok?'Opérationnel':'À vérifier'}</span></div>${Number.isFinite(latency)?`<div class="latency"><span>Latence</span><progress max="${maxLatency}" value="${latency}"></progress><strong>${fmt(latency)} ms</strong></div>`:''}</article>`;}).join('');$('#service-updated').textContent=`Sondé ${new Date(data.generatedAt).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}`;}

function setExportEnabled(enabled){for(const selector of ['#export-csv','#export-json']){const button=$(selector);if(button)button.disabled=!enabled;}}
function downloadFile(name,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportStamp(){return new Date().toISOString().replace(/[:.]/g,'-').slice(0,19);}
function exportJson(){if(!currentAnalytics)return;downloadFile(`meteocompare-admin-${days}j-${exportStamp()}.json`,JSON.stringify({exportedAt:new Date().toISOString(),analytics:currentAnalytics,status:currentStatus},null,2),'application/json;charset=utf-8');}
function csvCell(value){const text=String(value??'');return /[;"\n\r]/.test(text)?`"${text.replace(/"/g,'""')}"`:text;}
function exportRows(data,status){const rows=[['section','date','label','value','visitors','pageviews','events','successful','failed','status','latency_ms']];const push=(section,values={})=>rows.push([section,values.date||'',values.label||'',values.value??'',values.visitors??'',values.pageviews??'',values.events??'',values.successful??'',values.failed??'',values.status??'',values.latencyMs??'']);for(const [label,value] of Object.entries(data.summary||{}))push('summary',{label,value});for(const row of data.trend||[])push('audience_daily',{date:row.day,pageviews:row.pageviews,visitors:row.visitors,events:row.events});for(const row of data.hourly24||[])push('audience_hourly',{date:row.timestamp,pageviews:row.pageviews,visitors:row.visitors,events:row.events});const dimensions={pages:data.topPages,referrers:data.referrers,countries:data.countries,devices:data.devices,browsers:data.browsers,operating_systems:data.operatingSystems,languages:data.languages,display_modes:data.displayModes,navigation_modes:data.navigationModes,themes:data.themes,densities:data.densities,app_versions:data.appVersions,interactions:data.events,utm_sources:data.campaignSources,utm_mediums:data.campaignMediums,utm_campaigns:data.campaigns};for(const [section,items] of Object.entries(dimensions))for(const item of items||[])push(section,{label:item.label,value:item.value,visitors:item.visitors});const worker=data.workerVigilance||{};for(const row of worker.trend||[])push('vigilance_daily',{date:row.day,value:row.requests,successful:row.successful,failed:row.failed});for(const item of worker.clients||[])push('vigilance_clients',{label:item.label,value:item.value});for(const item of worker.cache||[])push('vigilance_cache',{label:item.label,value:item.value});for(const service of status?.services||[])push('service_status',{label:service.name,value:service.ok?'ok':'error',status:service.status,latencyMs:service.latencyMs});return rows;}
function exportCsv(){if(!currentAnalytics)return;const content='\ufeff'+exportRows(currentAnalytics,currentStatus).map(row=>row.map(csvCell).join(';')).join('\r\n');downloadFile(`meteocompare-admin-${days}j-${exportStamp()}.csv`,content,'text/csv;charset=utf-8');}

async function refresh(){const button=$('#refresh');button.disabled=true;button.classList.add('loading');try{const [analytics,status]=await Promise.all([api(`/_mcx/admin/analytics?days=${days}`),api('/_mcx/admin/status')]);currentAnalytics=analytics;currentStatus=status;renderAnalytics(analytics);renderServices(status);setExportEnabled(true);}catch(error){if(error.message!=='UNAUTHORIZED')console.error(error);}finally{button.disabled=false;button.classList.remove('loading');}}
$('#login-form').addEventListener('submit',async event=>{event.preventDefault();$('#login-error').textContent='';try{await api('/_mcx/admin/login',{method:'POST',body:JSON.stringify({password:$('#password').value})});$('#password').value='';showDashboard();await refresh();}catch(error){$('#login-error').textContent=error.message==='INVALID_CREDENTIALS'?'Mot de passe incorrect.':'Connexion impossible.';}});
$('#logout').addEventListener('click',async()=>{try{await api('/_mcx/admin/logout',{method:'POST',body:'{}'});}finally{currentAnalytics=null;currentStatus=null;showLogin();}});
$('#refresh').addEventListener('click',refresh);
$('#export-csv').addEventListener('click',exportCsv);
$('#export-json').addEventListener('click',exportJson);
document.querySelectorAll('[data-days]').forEach(button=>button.addEventListener('click',()=>{days=Number(button.dataset.days);document.querySelectorAll('[data-days]').forEach(item=>item.classList.toggle('active',item===button));void refresh();}));
(async()=>{try{const session=await api('/_mcx/admin/session');if(!session.configured){$('#login').hidden=true;$('#not-configured').hidden=false;return;}if(session.authenticated){showDashboard();await refresh();}else showLogin();}catch{showLogin();}})();
