const $=s=>document.querySelector(s);let days=30;
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'content-type':'application/json',...(options.headers||{})},cache:'no-store'});let body={};try{body=await r.json();}catch{}if(r.status===401){showLogin();throw new Error('UNAUTHORIZED');}if(!r.ok)throw new Error(body.error||`HTTP_${r.status}`);return body;}
function showLogin(){$('#login').hidden=false;$('#dashboard').hidden=true;$('#logout').hidden=true;}
function showDashboard(){$('#login').hidden=true;$('#not-configured').hidden=true;$('#dashboard').hidden=false;$('#logout').hidden=false;}
function fmt(n){return new Intl.NumberFormat('fr-FR').format(Number(n)||0)}
function list(el,items){const target=$(el);if(!items?.length){target.innerHTML='<p class="muted">Aucune donnée</p>';return;}const max=Math.max(...items.map(x=>Number(x.value)||0),1);target.innerHTML=items.map(x=>`<div class="list-row"><div><small>${escapeHtml(x.label||'—')}</small><div class="bar"><i style="width:${Math.max(2,(Number(x.value)||0)/max*100)}%"></i></div></div><strong>${fmt(x.value)}</strong></div>`).join('');}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function renderAnalytics(data){$('#metrics').innerHTML=[['Visiteurs',data.summary.visitors],['Pages vues',data.summary.pageviews],['Événements',data.summary.events]].map(([label,value])=>`<article class="metric card"><span>${label}</span><strong>${fmt(value)}</strong></article>`).join('');const max=Math.max(...(data.trend||[]).map(x=>Number(x.pageviews)||0),1);$('#trend').innerHTML=(data.trend||[]).map(x=>`<div class="trend-col" title="${escapeHtml(x.day)} · ${fmt(x.pageviews)} pages · ${fmt(x.visitors)} visiteurs"><i style="height:${Math.max(2,(Number(x.pageviews)||0)/max*140)}px"></i><small>${escapeHtml(String(x.day).slice(5))}</small></div>`).join('')||'<p>Aucune donnée</p>';for(const [id,key] of [['#pages','topPages'],['#referrers','referrers'],['#countries','countries'],['#devices','devices'],['#browsers','browsers'],['#events','events'],['#campaigns','campaigns']])list(id,data[key]);$('#updated').textContent=`Mis à jour ${new Date(data.generatedAt).toLocaleString('fr-FR')}`;}
function renderServices(data){$('#services').innerHTML=(data.services||[]).map(s=>`<article class="service card ${s.ok?'ok':''}"><span class="dot" aria-hidden="true"></span><div class="service-copy"><strong>${escapeHtml(s.name)}</strong><small>${s.detail?escapeHtml(s.detail):s.ok?`Opérationnel · ${s.latencyMs??0} ms`:`Indisponible${s.status?` · HTTP ${s.status}`:''}`}</small></div></article>`).join('');}
async function refresh(){try{const [a,s]=await Promise.all([api(`/_mcx/admin/analytics?days=${days}`),api('/_mcx/admin/status')]);renderAnalytics(a);renderServices(s);}catch(e){if(e.message!=='UNAUTHORIZED')console.error(e);}}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();$('#login-error').textContent='';try{await api('/_mcx/admin/login',{method:'POST',body:JSON.stringify({password:$('#password').value})});$('#password').value='';showDashboard();await refresh();}catch(e){$('#login-error').textContent=e.message==='INVALID_CREDENTIALS'?'Mot de passe incorrect.':'Connexion impossible.';}});
$('#logout').addEventListener('click',async()=>{try{await api('/_mcx/admin/logout',{method:'POST',body:'{}'});}finally{showLogin();}});$('#refresh').addEventListener('click',refresh);document.querySelectorAll('[data-days]').forEach(b=>b.addEventListener('click',()=>{days=Number(b.dataset.days);document.querySelectorAll('[data-days]').forEach(x=>x.classList.toggle('active',x===b));void refresh();}));
(async()=>{try{const session=await api('/_mcx/admin/session');if(!session.configured){$('#login').hidden=true;$('#not-configured').hidden=false;return;}if(session.authenticated){showDashboard();await refresh();}else showLogin();}catch{showLogin();}})();
