import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(`../../../${p}`,import.meta.url),'utf8');
const html=read('admin.html'),css=read('admin.css'),js=read('admin.js'),build=read('tools/build-site.mjs'),sw=read('sw.js');
const favicon=new URL('../../../favicon.ico',import.meta.url);
assert.match(html,/rel="icon" href="\/favicon\.ico"/,'admin must explicitly declare the root favicon');
assert.ok(fs.existsSync(favicon),'favicon.ico must exist at the public root');
assert.match(build,/favicon\.ico/,'production build must copy favicon.ico');
assert.match(sw,/\.\/favicon\.ico/,'PWA shell must precache the favicon');
assert.match(js,/function attentionIcon\(level\)/,'attention state must use a stable icon renderer');
assert.match(js,/<svg viewBox="0 0 24 24"/,'attention icons must be SVG rather than font glyphs');
assert.match(css,/\.attention-item \.attention-icon\{[^}]*display:grid[^}]*place-items:center/,'attention icon wrapper must center SVGs on both axes with a selector stronger than generic span rules');
assert.match(css,/\.attention-item \.attention-icon svg\{[^}]*width:16px[^}]*height:16px[^}]*margin:auto/,'attention SVG geometry must be fixed and explicitly centered');
assert.doesNotMatch(css,/\.attention-item strong,\.attention-item span\{display:block\}/,'generic span styling must not override the attention icon layout');
assert.match(css,/\.dimension-tabs\{display:grid;grid-template-columns:repeat\(4,minmax\(0,1fr\)\)/,'all environment dimension tabs must be visible in a wrapping grid');
assert.doesNotMatch(css,/\.dimension-tabs\{[^}]*overflow-x:auto/,'dimension tabs must not depend on a hidden horizontal scroller');
assert.match(css,/\.service-history-meta b\{[^}]*overflow-wrap:anywhere/,'long service metadata such as incident text must wrap');
assert.doesNotMatch(css,/\.service-history-meta b\{[^}]*white-space:nowrap/,'service metadata must not be forced onto one truncated line');
console.log('Admin favicon, attention icons, dimension tabs and wrapping metadata: OK');
