import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(`../../../${p}`,import.meta.url),'utf8');
const html=read('admin.html'),js=read('admin.js'),css=read('admin.css'),store=read('js/server/analytics-store.js'),worker=read('worker.js'),app=read('js/app.js');
assert.match(html,/Audience quotidienne/);
assert.match(html,/Dernières 24 heures/);
assert.match(html,/Systèmes/);
assert.doesNotMatch(html,/Sources UTM|Médiums UTM|Campagnes UTM/,'UTM dimensions must stay out of the admin interface');
assert.match(html,/Versions MeteoCompare/);
assert.match(html,/id="deployed-version"/,'admin header must expose the deployed-version badge');

assert.match(html,/assets\/icon\.png/,'admin must use the MeteoCompare application icon');
assert.match(html,/export-csv/);assert.match(html,/export-json/);
assert.match(html,/Requêtes Vigilance/);assert.match(html,/vigilance-trend-chart/);
assert.match(js,/chart-tooltip/);assert.match(js,/bindCartesianHover/,'admin charts must expose rich pointer hover information');
assert.match(js,/exportCsv/);assert.match(js,/exportJson/);
assert.doesNotMatch(js,/list\('#campaign-(?:sources|mediums)'|list\('#campaigns'/,'admin must not render UTM dimensions');
assert.match(js,/Version déployée · v/,'admin must render the deployed application version returned by status');
assert.match(worker,/appVersion:APP_VERSION/,'admin status must expose the centralized deployed application version');
assert.match(store,/CREATE TABLE IF NOT EXISTS worker_requests/);
assert.match(store,/workerVigilance/);
assert.match(store,/DELETE FROM worker_requests WHERE ts < \?/,'worker request retention must follow analytics retention');
assert.match(worker,/X-MeteoCompare-Client|x-meteocompare-client/);
assert.match(js,/renderTrend/);
assert.match(js,/renderHourly/);
assert.match(js,/renderDonut/);
assert.match(js,/previousSummary/);
assert.match(css,/\.trend-line\.pageviews/);
assert.match(css,/\.donut-segment\.segment-0/);
assert.match(store,/previousSummary/);
assert.match(store,/hourly24/);
assert.match(store,/operatingSystems/);
assert.match(store,/navigationModes/);
assert.match(store,/campaignMediums/,'UTM data remains available in analytics storage/export even when hidden from the admin UI');
assert.match(store,/CREATE TABLE IF NOT EXISTS maintenance/,'analytics retention must use deterministic maintenance state');
assert.match(store,/DELETE FROM events WHERE ts < \?/,'analytics retention must delete expired rows');
assert.doesNotMatch(store,/Math\.random/,'analytics retention must not depend on probabilistic cleanup');
assert.match(worker,/osFromUa/);
assert.match(app,/dateLabel\(bands\[i\]\.timestamp\.slice\(0,10\),i18n\(\)\.locale,'long'\)/,'hourly convergence axis must use localized long dates');
assert.doesNotMatch(app,/bands\[i\]\.timestamp\.slice\(5,10\)/,'hourly convergence axis must not expose raw month-day strings');

assert.match(app,/chart-date-guide/,'hourly convergence chart must draw visible vertical date guides above the band fills');
assert.match(css,/\.hour-line-halo/,'hourly admin visitor curve must have a contrast halo');
assert.match(css,/\.hour-dot/,'hourly admin visitor curve must expose visible data points');
assert.match(html,/legend-hour-pages[\s\S]*legend-hour-visitors/,'hourly admin chart must explain bars versus visitor line');
for(const locale of ['fr','en','de','es','it']){
  const text=read(`js/locales/${locale}.js`);
  assert.doesNotMatch(text,/la mesure d.audience interne de MeteoCompare/,'locale must not contain the broken mixed-language analytics phrase');
}
console.log('Rich private admin dashboard + localized convergence dates: OK');
