import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(`../../../${p}`,import.meta.url),'utf8');
const html=read('admin.html'),js=read('admin.js'),css=read('admin.css'),store=read('js/server/analytics-store.js'),worker=read('worker.js'),app=read('js/app.js');
assert.match(html,/Audience quotidienne/);
assert.match(html,/Dernières 24 heures/);
assert.match(html,/Systèmes/);
assert.match(html,/Médiums UTM/);
assert.match(html,/Versions MeteoCompare/);
assert.match(js,/renderTrend/);
assert.match(js,/renderHourly/);
assert.match(js,/renderDonut/);
assert.match(js,/previousSummary/);
assert.match(css,/\.trend-line\.pageviews/);
assert.match(css,/\.donut-segment\.segment-0/);
assert.match(store,/previousSummary/);
assert.match(store,/hourly24/);
assert.match(store,/operatingSystems/);
assert.match(store,/navigationModes/);
assert.match(store,/campaignMediums/);
assert.match(worker,/osFromUa/);
assert.match(app,/dateLabel\(bands\[i\]\.timestamp\.slice\(0,10\),i18n\(\)\.locale,'long'\)/,'hourly convergence axis must use localized long dates');
assert.doesNotMatch(app,/bands\[i\]\.timestamp\.slice\(5,10\)/,'hourly convergence axis must not expose raw month-day strings');
console.log('Rich private admin dashboard + localized convergence dates: OK');
