import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(`../../../${p}`,import.meta.url),'utf8');
const html=read('index.html'),transport=read('js/analytics-transport.js'),worker=read('worker.js'),network=read('js/network-config.js'),store=read('js/server/analytics-store.js'),wrangler=read('wrangler.jsonc'),sw=read('sw.js');
assert.match(html,/src="js\/analytics-transport\.js"/);
assert.match(worker,/sanitizeAnalyticsIngressPayload/);
assert.match(worker,/analyticsStub\(env\)/);
assert.match(worker,/ANALYTICS_HASH_SECRET/);
assert.doesNotMatch(worker,/ANALYTICS_HASH_SECRET\|\|env\?\.ADMIN_SESSION_SECRET/,'analytics hashing must never reuse the admin session secret');
assert.match(worker,/ANALYTICS_HASH_NOT_CONFIGURED/,'analytics ingestion must fail closed when its dedicated hashing secret is missing');
assert.match(worker,/ADMIN_SESSION_SECRET/);
assert.match(worker,/HttpOnly/);
assert.match(worker,/Secure/);
assert.match(worker,/SameSite=Strict/);
assert.match(worker,/isLocalCloudflareRequest/);
assert.match(store,/CREATE TABLE IF NOT EXISTS events/);
assert.match(store,/COUNT\(DISTINCT/);
assert.match(wrangler,/"new_sqlite_classes"/);
assert.match(wrangler,/"class_name": "AnalyticsStore"/);
assert.match(wrangler,/"\/admin"/);
assert.match(sw,/\['\/admin','\/admin\/','\/admin\.html','\/admin\.js','\/admin\.css'\]/);
assert.match(transport,/globalThis\.fetch\(ANALYTICS_CONFIG\.endpoint/);
assert.match(read('js/analytics-config.js'),/provider: 'meteocompare'/);
console.log('MeteoCompare internal analytics + private admin architecture: OK');
