import assert from 'node:assert/strict';
import fs from 'node:fs';
import { ANALYTICS_CONFIG } from '../../../js/analytics-config.js';

const read=rel=>fs.readFileSync(new URL(`../../../${rel}`,import.meta.url),'utf8');
const html=read('index.html'),bootstrap=read('js/mcx-events.js'),worker=read('worker.js'),network=read('js/network-config.js'),serverAnalytics=read('js/server/analytics-upstream.js'),wrangler=read('wrangler.jsonc'),preview=read('tools/preview-html.mjs');
assert.equal(ANALYTICS_CONFIG.endpoint,'/_mcx/e');
assert.match(html,/src="js\/mcx-events\.js"/);
assert.match(bootstrap,/ANALYTICS_CONFIG\.endpoint/);
assert.doesNotMatch(html,/<script[^>]+src="https:\/\/plausible\.io/);
assert.match(worker,/env\.ASSETS\.fetch\(request\)/);
assert.match(worker,/PLAUSIBLE_UPSTREAM_EVENT/);
assert.match(serverAnalytics,/https:\/\/plausible\.io\/api\/event/);
assert.match(worker,/MODEL_METADATA_PATH = NETWORK_ENDPOINTS\.firstParty\.modelMetadata/);
assert.match(network,/modelMetadata: '\/_mcx\/model-metadata'/);
assert.match(network,/map-tiles\.open-meteo\.com\/data_spatial/);
assert.match(worker,/MODEL_METADATA_KEY/);
assert.match(worker,/forecast-run-fallback/);
assert.match(worker,/UPSTREAM_HTTP_/);
assert.match(worker,/fetchUpstream/);
assert.match(worker,/ANALYTICS_MAX_BODY_BYTES/);
assert.match(worker,/sanitizePlausibleProxyPayload/,'Worker must revalidate analytics payloads server-side');
assert.match(worker,/cf-connecting-ip/);
assert.match(worker,/x-forwarded-for/);
assert.match(worker,/status:timedOut\?504:502/);
assert.match(wrangler,/"main": "\.\/worker\.js"/);
assert.match(wrangler,/"binding": "ASSETS"/);
assert.match(wrangler,/"run_worker_first": \["\/_mcx\/\*"\]/);
assert.match(bootstrap,/globalThis\.fetch\(ANALYTICS_CONFIG\.endpoint/,'browser must use the opaque first-party endpoint');
assert.doesNotMatch(bootstrap,/https:\/\/plausible\.io|createElement\(['"]script['"]\)/,'browser must never load or contact Plausible directly');
assert.doesNotMatch(network,/upstreamScript|analyticsScript|plausible\.io/,'Plausible upstream must not be part of the browser data plane');
assert.doesNotMatch(worker,/proxyPlausibleScript|SCRIPT_PATH/,'Worker should proxy events only, not a browser tracker script');
assert.match(preview,/host-gated/,'local preview relies on host-gated analytics transport');
console.log('MeteoCompare first-party Plausible Cloudflare proxy: OK');
