import assert from 'node:assert/strict';
import fs from 'node:fs';

const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const html=read('index.html'), app=read('js/app.js'), css=read('styles.css'), storage=read('js/storage.js'), sw=read('sw.js');

assert.doesNotMatch(html, /id="app"[^>]*aria-live=/, 'the whole application must not be an aria-live region');
assert.match(html, /id="toast-root"[^>]*aria-live="polite"/, 'toasts should use a non-interruptive live region');
assert.match(html, /Content-Security-Policy/, 'a document CSP should constrain executable and network resources');
assert.match(html, /connect-src[^"]*api\.open-meteo\.com/, 'CSP should allow only the required weather endpoints');
assert.match(app, /e\.key==='Escape'&&state\.modal/, 'Escape must close modals');
assert.match(app, /querySelectorAll\('button:not\(\[disabled\]\).*tabindex/, 'modal focus must be trapped');
assert.match(app, /\[data-city-open\]\[role="link"\]/, 'city cards must be keyboard activatable');
assert.match(app, /data-scroll-section="today-summary"/, 'detail navigation must not conflict with hash routing');
assert.match(app, /class="global-agreement\s/, 'TodaySummary must restore global agreement');
assert.match(app, /data-action="why-confidence"/, 'TodaySummary must expose the agreement explanation action');
assert.match(app, /renderTableLegend\(tab,mode,normals\)/, 'detailed tables must render legends');
assert.match(app, /heatmap-data-cell/, 'detailed tables must render heatmap cells');
assert.match(app, /renderTableBiasChip/, 'table model headers must render local bias chips');
assert.doesNotMatch(app, /function renderInlineBias/, 'bias values must not be repeated inside every forecast cell');
assert.match(app, /name:'bias'/, 'each model bias must have a dedicated web route');
assert.match(app, /function renderBiasDetailPage/, 'a dedicated model bias page must be implemented');
assert.match(css, /tr:nth-child\(even\) td\.heatmap-data-cell\[style\*="--heat"\]/, 'even heatmap rows must preserve their heat colors');
assert.match(app, /data-timeline-mode="HOURLY"/, 'rich timeline must expose 24h mode');
assert.match(app, /data-timeline-mode="DAILY"/, 'rich timeline must expose daily mode');
assert.doesNotMatch(app, /href="#today-summary"/, 'hash routing must not be overwritten by section anchors');
assert.equal((app.match(/searchMinChars/g)||[]).length,1,'search hint must be centralized through one i18n key');
assert.match(css, /--content-max:\s*1560px/, 'modern desktop layout should use a wide canvas');
assert.match(css, /@media \(max-width: 560px\)/, 'mobile fallback must remain responsive');
assert.match(css, /prefers-reduced-motion:\s*reduce/, 'reduced-motion preference must be supported');

assert.equal((app.match(/data-action="refresh-all"/g)||[]).length,1,'refresh-all must appear only as a page-level action, not duplicated in the top bar');
assert.equal((app.match(/data-action="settings"/g)||[]).length,1,'settings must appear only once in the global navigation');
assert.match(app, /history\.scrollRestoration='manual'/, 'browser-native scroll restoration must be disabled so the app has deterministic route positioning');
assert.match(app, /applyRouteFromLocation\(0,\{newRoute:true\}\)/, 'new routes, including model bias pages, must use the dedicated top-reset transition');
assert.match(app, /immediate:true/, 'route transitions must render immediately instead of leaving the clicked control focused for another frame');
assert.match(app, /focusRouteLandmark/, 'new routes must move focus to the new page landmark without scrolling');
assert.match(app, /requestAnimationFrame\(\(\)=>\{pin\(\);requestAnimationFrame\(pin\);\}\)/, 'route-top reset must survive delayed browser focus/fragment restoration');
assert.match(app, /history\.replaceState\(\{\.\.\.history\.state,mcRouteKey:key,mcScrollY:y\}/, 'route entries must persist their scroll position for Back/Forward restoration');
assert.match(app, /captureScrollContext\(target=null\)/, 'same-view controls must capture a stable viewport context before rerendering');
assert.match(app, /type:'selector',selector,top:target\.getBoundingClientRect\(\)\.top/, 'interactive controls must preserve their exact viewport coordinate across rerenders');
assert.match(app, /type:'anchor',id:section\.id/, 'section anchors must remain as a fallback for controls without a stable selector');
assert.match(app, /chart-band-segment \$\{level\}/, 'the min-max agreement envelope must be segmented and confidence-colored');
assert.match(css, /\.chart-band-segment\.high[^}]*fill:\s*var\(--good\)/s, 'high-agreement envelope segments must use the good color');
assert.match(css, /\.chart-band-segment\.medium[^}]*fill:\s*var\(--medium\)/s, 'medium-agreement envelope segments must use the medium color');
assert.match(css, /\.chart-band-segment\.low[^}]*fill:\s*var\(--low\)/s, 'low-agreement envelope segments must use the low color');
assert.match(app, /class="model-header-stack"/, 'table model headers must reserve separate rows for metadata and bias state');
assert.match(app, /class="model-bias-slot"/, 'table bias/calibration pills must live in a dedicated model-header slot');
assert.match(app, /bias-chip bias-chip-button pending table-bias-chip[^>]*data-bias-model=/, 'calibration pills must remain clickable and open the model reliability page');

assert.match(css, /\.overview-primary\s*\{[^}]*display:\s*flex/s, 'TodaySummary column must stretch to the full overview height');
assert.match(css, /\.overview-primary \.today-grid\s*\{[^}]*grid-template-columns:\s*repeat\(2/s, 'TodaySummary variables should use a 2x2 desktop matrix');
assert.match(css, /Modern professional UI/, 'the modern professional visual layer must be present');
assert.match(css, /professional-hero::before, \.professional-hero::after \{ display: none; \}/, 'decorative hero grids must be disabled');
assert.match(css, /\.chart-wrap \{ background: var\(--surface\); background-image: none; \}/, 'chart containers must not use decorative graph-paper backgrounds');
assert.match(css, /\.topbar-system-status/, 'the data availability status must remain visible without terminal styling');
assert.match(app, /onlineData/, 'top bar should use the localized online status text');
assert.match(app, /class="settings-section settings-wide history-management"/, 'costly bias-history refresh must be centralized in Settings');
assert.match(app, /costlyOperation/, 'history management must clearly warn that archive reconstruction is costly through i18n');
assert.match(app, /function renderBiasHistoryManagementRow/, 'Settings must expose per-city history management rather than a global refresh-everything action');
assert.match(app, /class="btn tonal history-refresh-action" data-bias-refresh-city=/, 'history refresh must remain available per city from the dedicated Settings area');
assert.doesNotMatch(app, /data-action="refresh-bias-all"/, 'the expensive refresh-all action must not be exposed');
assert.doesNotMatch(app, />Actualiser l’historique<\/button>/, 'model bias pages must not expose costly history-refresh buttons');
assert.match(storage, /indexedDB/, 'large forecast payloads should use IndexedDB');
assert.match(storage, /loadForecastAsync/, 'legacy forecast cache migration must be present');
assert.match(storage, /export async function saveForecast/, 'forecast persistence should be awaitable');
assert.match(storage, /database\?\.close/, 'clearing local data should close IndexedDB before deleting it');
assert.match(app, /refreshCity\(city\.id,false,false\)/, 'automatic multi-city refresh should suppress per-city full renders');
assert.match(app, /refreshCity\(c\.id,force,false\)/, 'manual multi-city refresh should suppress per-city full renders');
assert.match(sw, /request\.mode==='navigate'/, 'service worker must have explicit navigation handling');
assert.match(sw, /open-meteo\\\.com/, 'Open-Meteo responses must not be mixed with the shell cache');
assert.ok(Number(sw.match(/CACHE_VERSION\s*=\s*['"]v(\d+)/)?.[1] || 0) >= 18, 'PWA cache version must not regress below v18');
assert.match(css, /#app \{ overflow-anchor: none; \}/, 'browser scroll anchoring must not fight the explicit viewport restoration logic');
assert.doesNotMatch(css, /\.section, \.city-card, \.settings-section \{ content-visibility: auto/, 'detail sections must not use estimated off-screen heights that can cause scroll jumps');
assert.doesNotMatch(css, /\.settings-section[^}]*content-visibility:\s*auto/s, 'Settings sections must remain fully laid out to avoid click/focus scroll jumps');
assert.match(css, /\.settings-list[^}]*overflow-anchor:\s*none/s, 'Settings must disable native scroll anchoring so it cannot fight explicit viewport stabilization');
assert.match(css, /\.city-card\s*\{[^}]*content-visibility:\s*auto/s, 'home city cards may retain off-screen rendering optimization');
assert.match(app, /data-theme[^\n]+stabilizeLocalScroll\(interactionScrollContext\)/, 'theme updates must repin the clicked Settings control');
assert.match(app, /data-density[^\n]+stabilizeLocalScroll\(interactionScrollContext\)/, 'density updates must repin the clicked Settings control');
console.log('MeteoCompare Web static audit tests: OK');
