import assert from 'node:assert/strict';
import fs from 'node:fs';

const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const html=read('index.html'), app=read('js/app.js'), css=read('styles.css'), storage=read('js/storage.js'), sw=read('sw.js');

assert.doesNotMatch(html, /id="app"[^>]*aria-live=/, 'the whole application must not be an aria-live region');
assert.match(html, /id="toast-root"[^>]*aria-live="polite"/, 'toasts should use a non-interruptive live region');
assert.match(html, /Content-Security-Policy/, 'a document CSP should constrain executable and network resources');
assert.match(html, /connect-src[^"]*api\.open-meteo\.com/, 'CSP should allow only the required weather endpoints');
assert.match(app, /e\.key==='Escape'&&state\.modal/, 'Escape must close modals');
assert.match(app, /querySelectorAll\('button:not\(\[disabled\]\).*tabindex/, 'modal focus must be trapped');
assert.match(app, /\[data-city-open\]\[role="link"\]/, 'city cards must be keyboard activatable');
assert.match(app, /data-scroll-section="today-summary"/, 'detail navigation must not conflict with hash routing');
assert.match(app, /class="global-agreement\s/, 'TodaySummary must restore global agreement');
assert.match(app, /data-action="why-confidence"/, 'TodaySummary must expose the agreement explanation action');
assert.match(app, /renderTableLegend\(tab,mode,normals\)/, 'detailed tables must render legends');
assert.match(app, /heatmap-data-cell/, 'detailed tables must render heatmap cells');
assert.match(app, /data-timeline-mode="HOURLY"/, 'rich timeline must expose 24h mode');
assert.match(app, /data-timeline-mode="DAILY"/, 'rich timeline must expose daily mode');
assert.doesNotMatch(app, /href="#today-summary"/, 'hash routing must not be overwritten by section anchors');
assert.equal((app.match(/Saisissez au moins 3 caractères\./g)||[]).length,1,'search hint must not be duplicated');
assert.match(css, /--content-max:\s*1600px/, 'technical desktop layout should use a wide canvas');
assert.match(css, /@media \(max-width: 560px\)/, 'mobile fallback must remain responsive');
assert.match(css, /prefers-reduced-motion:\s*reduce/, 'reduced-motion preference must be supported');

assert.match(css, /\.overview-primary\s*\{[^}]*display:\s*flex/s, 'TodaySummary column must stretch to the full overview height');
assert.match(css, /\.overview-primary \.today-grid\s*\{[^}]*grid-template-columns:\s*repeat\(2/s, 'TodaySummary variables should use a 2x2 desktop matrix');
assert.match(css, /--tech-font:/, 'technical UI must expose a dedicated numeric/readout font stack');
assert.match(css, /\.topbar-system-status/, 'technical chrome should expose the live/cache data status');
assert.match(app, /DATA LIVE/, 'top bar should render the technical online data indicator');
assert.match(storage, /indexedDB/, 'large forecast payloads should use IndexedDB');
assert.match(storage, /loadForecastAsync/, 'legacy forecast cache migration must be present');
assert.match(storage, /export async function saveForecast/, 'forecast persistence should be awaitable');
assert.match(storage, /database\?\.close/, 'clearing local data should close IndexedDB before deleting it');
assert.match(app, /refreshCity\(city\.id,false,false\)/, 'automatic multi-city refresh should suppress per-city full renders');
assert.match(app, /refreshCity\(c\.id,force,false\)/, 'manual multi-city refresh should suppress per-city full renders');
assert.match(sw, /request\.mode==='navigate'/, 'service worker must have explicit navigation handling');
assert.match(sw, /open-meteo\\\.com/, 'Open-Meteo responses must not be mixed with the shell cache');
assert.match(sw, /v6-technical-ui/, 'service worker cache must be bumped for the technical UI release');
console.log('MeteoCompare Web static audit tests: OK');
