import fs from 'node:fs';
import assert from 'node:assert/strict';
const css=fs.readFileSync(new URL('../../../styles.css',import.meta.url),'utf8');
assert.match(css,/\.about-visual-step\{[^}]*min-width:0[^}]*max-width:100%[^}]*overflow:hidden/s,'About steps must be shrinkable inside the mobile viewport');
assert.match(css,/\.about-visual-step-scene\{[^}]*width:100%[^}]*max-width:100%[^}]*overflow:hidden/s,'About scenes must remain inside each step card');
assert.match(css,/\.about-method-flow:not\(\.about-visual-steps\) article/,'generic About cards must not leak into the visual explainer');
assert.doesNotMatch(css,/\.about-method-flow\.about-visual-steps > \.about-visual-step/,'visual steps must not need specificity workaround selectors');
assert.match(css,/@media\(max-width:980px\)\{[\s\S]*?\.about-visual-step\{grid-template-columns:1fr;/,'visual steps must become one column through their own component rule');
assert.match(css,/@media\(max-width:640px\)[\s\S]*?\.about-visual-radar-frames\{\s*grid-template-columns:repeat\(3,minmax\(0,1fr\)\);\s*overflow:visible;/,'mobile radar explainer must reflow instead of overflowing horizontally');
console.log('mobile About visual scenes regression test passed');
