import assert from 'node:assert/strict';
import fs from 'node:fs';

const app=fs.readFileSync(new URL('../../../js/app.js',import.meta.url),'utf8');
const fr=fs.readFileSync(new URL('../../../js/locales/fr.js',import.meta.url),'utf8');
const network=fs.readFileSync(new URL('../../../js/network-config.js',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('../../../index.html',import.meta.url),'utf8');
const styles=fs.readFileSync(new URL('../../../styles.css',import.meta.url),'utf8');

const renderTimeline=app.slice(app.indexOf('function renderTimeline('),app.indexOf('function renderConfidenceSection('));
const renderPoint=app.slice(app.indexOf('function timelineMetricRail('),app.indexOf('function timelineEventMarker('));
assert.match(renderTimeline,/selectRegularTimelinePoints\(analysis,mode==='HOURLY'\?24:7,1\)/,'detail 24 h timeline must render hourly points');
assert.match(app,/function homeTimelinePoints\(f,forecastOptions,maxPoints=12,now=new Date\(\),stepHours=1\)[\s\S]*selectRegularTimelinePoints\(buildTimelinePoints\(f,'HOURLY'[\s\S]*maxPoints,stepHours\)/,'home mini timeline must expose 12 consecutive hourly points');
assert.match(app,/disagreementAnalysis\(cityId\)[\s\S]*selectRegularTimelinePoints\(buildTimelinePoints\(f,'HOURLY',new Date\(\),opts\),24,1\)/,'detail disagreement analysis must use the same hourly grid');
assert.match(fr,/"next24Regular":"Prochaines 24 heures · repères chaque heure"/);
assert.doesNotMatch(html,/openmeteo-data-spatial\.b-cdn\.net/,'browser CSP no longer needs a direct metadata CDN connection');
assert.match(styles,/timeline-ruler, \.timeline-full \{ grid-template-columns: repeat\(var\(--timeline-cols, 8\), minmax\(148px,1fr\)\); \}/,'hourly timeline columns must have enough width for condition labels');
assert.match(styles,/timeline-condition > span:last-child \{[^}]*white-space:normal;[^}]*-webkit-line-clamp:2;/,'weather condition labels must use a stable two-line area instead of ellipsis');
assert.match(styles,/timeline-point-head span \{[^}]*white-space:normal;[^}]*-webkit-line-clamp:2;/,'localized timeline dates must be readable on two lines');
assert.match(renderPoint,/engineDetail\?\.allSourceInterval\|\|engineDetail\?\.interval/,'timeline rails must distinguish the probable all-source interval');
assert.match(renderPoint,/retainedInterval=normalizedInterval\(engineDetail\?\.interval\)/,'timeline rails must retain the selected engine interval separately');
assert.match(renderPoint,/precipitationExpectedMinAcrossModelsMm[\s\S]*engineDetails\?\.precipitation/,'rain rail must compare expected precipitation on one consistent scale');
assert.match(renderPoint,/engineDetails\?\.cloud[\s\S]*engineDetails\?\.wind/,'cloud and wind timeline metrics must consume their engine intervals');
assert.match(renderPoint,/timeline-rain-probability-metric[\s\S]*timeline-rain-amount-metric/,'rain probability and probabilistic accumulation must use distinct timeline rows');
assert.match(renderPoint,/precipitationProbabilityMin[\s\S]*engineDetail:null[\s\S]*precipitationExpectedMinAcrossModelsMm/,'probability spread must stay separate from amount intervals');
assert.match(renderPoint,/windGustMinAcrossModels[\s\S]*engineDetails\?\.gust[\s\S]*timeline-gust-metric/,'gusts must be promoted to their own metric with a complete engine rail');
assert.match(renderPoint,/renderMetric\('precipitation-probability'[\s\S]*renderMetric\('precipitation-amount'[\s\S]*renderMetric\('wind'[\s\S]*renderMetric\('gust'/,'probability, accumulation, wind and gusts must use semantically distinct glyphs');
assert.match(renderPoint,/timeline-metric-label[\s\S]*timelineRainProbabilityShort[\s\S]*timelineRainAmountShort/,'narrow metric rows must expose short labels rather than hiding long descriptions');
assert.match(renderTimeline,/summaryRainExpectedLabel[\s\S]*windMedianLegend[\s\S]*gusts[\s\S]*timeline-rail-legend/,'the chronology legend must name weighted rain and gusts separately');
assert.match(renderTimeline,/timeline-rail-legend[\s\S]*summarySpreadLegend[\s\S]*summaryIntervalLegend/,'the chronology legend must explain spread and intervals once globally');

assert.match(app,/class="detail-chrono-view" data-chrono-mode="\$\{attr\(mode\)\}"/,'chronological strip must expose its hourly/daily mode for layout tuning');
assert.match(app,/const dateGroups=\[\];[\s\S]*detail-chrono-date-cell[\s\S]*grid-column:span \$\{group\.span\}/,'chronological strip must group dates in a dedicated top row');
assert.match(app,/detail-chrono-canvas"><div class="detail-chrono-date">\$\{dates\}<\/div><svg class="detail-chrono-temp-plot"/,'date row must be rendered above temperature, conditions and all metric lanes');
assert.match(app,/detail-chrono-row-label date[\s\S]*dateColumn[\s\S]*detail-chrono-row-label temp/,'fixed first column must expose a dedicated Date row above Temperature');
assert.match(styles,/--detail-chrono-date-height:42px;/,'chronological strip must reserve explicit height for the date row');
assert.match(styles,/grid-template-rows:var\(--detail-chrono-date-height\) var\(--detail-chrono-temp-height\) var\(--detail-chrono-axis-height\)/,'fixed labels must align with the dedicated date lane');
assert.match(styles,/\.detail-chrono-date \{[^}]*grid-template-columns:repeat\(var\(--detail-chrono-cols\),minmax\(0,1fr\)\);/,'date row must stay synchronized with the chronology columns');
assert.doesNotMatch(app,/detail-chrono-axis-hour[^`]*<small>/,'condition cells must no longer carry a second date line');
assert.match(styles,/--detail-chrono-label-width:136px;/,'chronological strip must reserve a wider first column for row labels');
assert.match(app,/function divergenceIcon\(x\)[\s\S]*renderMetric\('temperature'[\s\S]*renderMetric\('precipitation'[\s\S]*renderMetric\('wind'[\s\S]*render\('PARTLY_CLOUDY'/,'chronological convergence warnings must use distinct weather icons for the affected variables');
assert.match(app,/detail-chrono-disagreement-icons[\s\S]*reasons\.map\(reason=>[\s\S]*divergenceIcon\(reason\)/,'chronological convergence warnings must render one icon per affected variable');
assert.match(styles,/\.modal-head > div:first-child \{ flex:1; min-width:0; \}/,'wrapped modal titles must claim the available header width');
assert.match(styles,/\.modal-head > \.icon-btn \{ flex:0 0 auto; margin-left:auto; \}/,'modal close action must stay pinned to the far right, including Understand convergence');
console.log('detail hourly timeline: OK');
