import assert from 'node:assert/strict';
import fs from 'node:fs';
import { APP_VERSION } from '../../../js/version.js';
const read=p=>fs.readFileSync(new URL(`../../../${p}`,import.meta.url),'utf8');
const app=read('js/app.js'),appState=read('js/core/app-state.js'),css=read('styles.css'),version=APP_VERSION,versionJs=read('js/version.js'),sw=read('sw.js');
assert.ok(versionJs.includes('APP_VERSION = globalThis.METEOCOMPARE_APP_VERSION'));
assert.ok(sw.includes('APP_VERSION = globalThis.METEOCOMPARE_APP_VERSION'));
assert.match(css,/\.timeline-metric\s*\{[\s\S]*height:\s*64px;[\s\S]*min-height:\s*64px;[\s\S]*grid-template-rows:\s*18px 10px 16px;/,'timeline metrics must share a fixed compact header, rail and detail geometry');
assert.match(css,/\.timeline-metric strong\s*\{[\s\S]*white-space:\s*nowrap/,'timeline metric values must not grow rows');
assert.match(css,/\.timeline-metric small\s*\{[\s\S]*overflow:\s*visible;[\s\S]*text-overflow:\s*clip/,'short metric details must stay visible instead of becoming ellipses');
assert.match(css,/\.timeline-dispersion-rail\s*\{[\s\S]*grid-column:\s*2 \/ -1;[\s\S]*height:\s*10px;/,'timeline dispersion rails must use the full text width below the compact header');
assert.match(css,/\.timeline-dispersion-probable\s*\{[\s\S]*background:\s*color-mix/,'timeline rails must expose the probable interval');
assert.match(css,/\.timeline-dispersion-retained\s*\{[\s\S]*background:\s*currentColor;/,'timeline rails must expose the engine-retained interval');
assert.match(appState,/localDataUi=\{advancedOpen:false,privacyOpen:false,cacheOpen:false\}/,'local data details state missing');
assert.match(app,/data-storage-advanced/);
assert.match(app,/refreshLocalDataStats\(interactionScrollContext\)/,'local data refresh must retain click anchor');
assert.match(app,/runIntegrityCheck\(false,interactionScrollContext\)/,'integrity check must retain click anchor');
assert.match(app,/class="model-settings-grid"/,'compact settings model grid missing');
assert.match(app,/class="model-row-head"/,'model switch must sit beside model name');
assert.match(css,/\.model-settings-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(2/);
assert.match(css,/\.about-mini-badge::before/,'about badge marker missing');
assert.match(css,/\.about-callout,[\s\S]*margin:\s*14px 0 0;/,'about callout spacing must be uniform');
console.log('tests/ui/regression/app.interaction-polish.test.mjs: OK');
