import fs from 'node:fs';
import assert from 'node:assert/strict';
import { APP_VERSION } from '../../../js/version.js';
const root=new URL('../../../',import.meta.url);
const app=fs.readFileSync(new URL('js/app.js',root),'utf8');
const css=fs.readFileSync(new URL('styles.css',root),'utf8');
const version=APP_VERSION;
const versionJs=fs.readFileSync(new URL('js/version.js',root),'utf8');
assert.ok(versionJs.includes('APP_VERSION = globalThis.METEOCOMPARE_APP_VERSION'));
assert.match(app,/class="summary-solar-pair"/,'TodaySummary must group solar chips');
assert.match(app,/class="summary-solar-chip"/,'TodaySummary solar chips must use dedicated geometry');
assert.match(css,/\.summary-context-chips > \.summary-solar-pair\s*\{/,'solar pair layout rule missing');
assert.match(css,/flex:\s*0 0 auto/,'solar pair must wrap as a single unit');
assert.match(css,/min-height:\s*26px/,'shared badge baseline missing');
assert.match(css,/\.summary-context-chips > \.summary-solar-pair\s*\{/,'final design polish rules must remain present without relying on historical release comments');
console.log('tests/ui/regression/styles.final-polish.test.mjs: OK');
