import fs from 'node:fs';
import assert from 'node:assert/strict';
import { APP_VERSION } from '../../../js/version.js';
const read=p=>fs.readFileSync(new URL('../../../'+p,import.meta.url),'utf8');
const version=APP_VERSION,versionJs=read('js/version.js'),sw=read('sw.js'),app=read('js/app.js'),css=read('styles.css');
assert.match(versionJs,/APP_VERSION = globalThis\.METEOCOMPARE_APP_VERSION/);
assert.match(sw,/APP_VERSION = globalThis\.METEOCOMPARE_APP_VERSION/);
assert.match(sw,/CACHE_VERSION = globalThis\.METEOCOMPARE_CACHE_VERSION/);
const home=app.slice(app.indexOf('function homeTimelinePoints'),app.indexOf('function renderCityDetail'));
assert.match(home,/class="home-hero"/);
assert.match(home,/home-city-grid/);
assert.match(home,/home-weather-timeline/);
assert.doesNotMatch(home,/home-mini-timeline/,'the old slot-based mini timeline must be removed');
assert.match(home,/homeTimelinePoints\(f,engineContext,12\)/,'home cards must request the complete 12-hour rail');
assert.match(home,/class="home-weather-timeline-scroll" role="region" tabindex="0"[^>]*><div class="home-weather-timeline"/,'the weather timeline must remain keyboard-scrollable and labelled');
assert.match(home,/class="home-temperature-plot"/,'the timeline must contain a real temperature graph');
assert.match(home,/class="home-weather-axis"/,'hourly conditions must form the graph x-axis');
assert.match(home,/class="home-weather-event-lane"/,'weather events must have a dedicated temporal lane');
assert.match(home,/groupRainTimelineEvents/,'rain events must be grouped as temporal episodes');
assert.doesNotMatch(home,/renderHomeConsensusStrip|home-consensus-rail/);
assert.match(home,/homeWatchCandidate/);
assert.match(home,/home-watch-section/);
assert.doesNotMatch(home,/dashboard-kpis/);
assert.match(css,/\.home-city-grid\s*\{[^}]*grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/s);
assert.match(css,/@media \(max-width: 980px\)[\s\S]*?\.home-city-grid \{ grid-template-columns:1fr; \}/);
assert.match(css,/\.home-city-card:hover/);
assert.match(css,/\.home-weather-timeline-scroll\s*\{[^}]*overflow-x:auto;[^}]*scroll-snap-type:inline proximity;[^}]*padding-bottom:5px;/s,'the scrollbar must sit below the timeline content');
assert.match(css,/\.home-weather-timeline\s*\{[^}]*width:max\(100%,calc\(var\(--home-timeline-cols\) \* var\(--home-timeline-step\)\)\);[^}]*min-width:calc\(var\(--home-timeline-cols\) \* 58px\);/s,'the 12-hour chart must preserve a readable horizontal scale');
assert.match(css,/\.home-weather-axis\s*\{[^}]*grid-template-columns:repeat\(var\(--home-timeline-cols\),minmax\(0,1fr\)\)/s,'conditions must stay aligned to hourly graph columns');
assert.match(css,/\.home-weather-axis-hour\s*\{[^}]*scroll-snap-align:start;/s,'hourly x-axis cells must snap without widening the card');
assert.doesNotMatch(css,/\.home-consensus-rail/);
assert.match(css,/\.home-watch-grid/);
for(const lang of ['fr','en','es','de','it']){
  const locale=read(`js/locales/${lang}.js`);
  for(const key of ['homeModernKicker','homeModernLead','homeSearchPrompt','homeConsensusTitle','homeWatchTitle','homeAgreementUnavailable','homeFamilyCountOne']) assert.match(locale,new RegExp(key));
}
console.log('tests/home/regression/app.layout.test.mjs: OK');
