import fs from 'node:fs';
import assert from 'node:assert/strict';
import { APP_VERSION } from '../../../js/version.js';
const read=p=>fs.readFileSync(new URL('../../../'+p,import.meta.url),'utf8');
const version=APP_VERSION,app=read('js/app.js'),css=read('styles.css'),sw=read('sw.js');
assert.match(sw,/APP_VERSION = globalThis\.METEOCOMPARE_APP_VERSION/);
assert.match(sw,/CACHE_VERSION = globalThis\.METEOCOMPARE_CACHE_VERSION/);
const home=app.slice(app.indexOf('function homeForecastEngineContext'),app.indexOf('function renderCityDetail'));
assert.match(home,/class="home-hero"/);
assert.match(home,/homeModernKicker/);
assert.doesNotMatch(home,/homeModernTitle|<h1>/,'Home hero must stay title-free');
assert.match(home,/homeModernLead/);
assert.match(home,/home-hero-actions/);
assert.match(home,/data-action="open-add-city"/);
assert.match(home,/data-action="open-city-compare"/);
assert.match(home,/data-action="refresh-all"/);
assert.doesNotMatch(home,/home-hero-mark/);
assert.doesNotMatch(home,/home-city-shortcut/);
assert.match(home,/homeTemperatureHeatColor/);
assert.match(home,/--heat-color:/);
assert.doesNotMatch(home,/--heat-hue:/);
assert.match(home,/home-heat-key/);
assert.doesNotMatch(home,/renderHomeConsensusStrip|home-consensus-rail|home-model-dot/);
assert.match(home,/homeCoherenceLabel/);
assert.match(home,/home-weather-coherence/);
assert.match(home,/precipitationConditionalMm/);
assert.match(home,/tempMinMax/);
const card=home.slice(home.indexOf('function renderCityCard'),home.indexOf('function comparisonRenderContext'));
assert.match(card,/home-weather-facts/);
assert.doesNotMatch(card,/home-weather-range/);
assert.doesNotMatch(card,/homeModelSignal/);
assert.doesNotMatch(card,/t\('temperature'\)\}\<\/small\>/,'Min/max fact must not repeat the Temperature label below itself');
assert.match(css,/\.home-dashboard\s*\{[^}]*grid-template-columns:minmax\(0,1fr\) minmax\(285px,330px\)/s);
assert.match(css,/\.home-watch-section\s*\{[^}]*position:sticky/s);
assert.match(css,/\.home-watch-section::before\s*\{[^}]*content:none/s);
assert.match(css,/\.home-dashboard\s*\{[^}]*margin-top:var\(--space-7\)/s);
assert.match(css,/\.home-weather-coherence/);
assert.match(css,/\.home-mini-hour\s*\{[^}]*--heat-color|\.home-mini-hour\s*\{[^}]*background:linear-gradient/s);
assert.match(css,/\.home-heat-key i\s*\{[^}]*linear-gradient\(90deg,#5b6ff9/s);
assert.match(css,/\.home-city-card\s*\{[^}]*contain-intrinsic-size:auto 455px/s);
console.log('tests/home/regression/styles.layout-polish.test.mjs: OK');
